name: ecommerce_base_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ecommerce_micro_core:
  ecommerce_micro_app_login:
  ecommerce_micro_app_home:

dependency_overrides:
  ecommerce_micro_core:
    path: ../ecommerce_micro_core
  ecommerce_micro_app_login:
    path: ../ecommerce_micro_app_login
  ecommerce_micro_app_home:
    path: ../ecommerce_micro_app_home
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
